# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jack Dexter Blog
email: jack.dexter73@blog.com
description: > # this means to ignore newlines until "baseurl:"
  "I have spent my life searching for the answers that my father and my father's fathers failed to find. Who are we? Why do we create the vast monoliths that litter our planet? How do we harness our power? And why do we so often fail to use it? What is our purpose? I have asked the plants, but they do not remember. The plants have asked the rocks, but the rocks do not recall. Even the rocks do not recall. Every bone in my body tells me that the answers rest ... in every single one of us... oblivious to our destiny, uninterested in the search for truth, and rejecting guidance! And why would you want to listen to this blog, anyway? So it seems the answers begin with careful research, sensible thinking and as with many of fate's mysteries, it begins with a small amount of disobedience."
  Hommage à Samos the Green Sage

baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://jackdexter73.github.io/cards/" # the base hostname & protocol for your site

#sidebar
default-image: JackDexterlogo.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

#built-by: JackDexter

copyright:
   name: JackDexter
  # link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
#analytics: UA-83979019-1

# Comments
#disqus: yes
#disqus-shortname: webjeda-demo

#social
#facebook: http://facebook.com/webjeda
#quora: http://quora.com/sharathdt
#twitter: http://twitter.com/@webjeda
#github: http://github.com/webjeda
#email: hello@webjeda.com

#facebook like box
#fb-like-box: yes
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/webjeda/
#fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]
